name: Scrape latest data

on:
  push:
    push:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      -
        name: "Check out this repo"
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: update public file listings
        working-directory: .
        run: |
          python rss_parser.py
      -
        name: "Commit and push if it changed"
        run: |-
            git config user.name "Automated"
            git config user.email "actions@users.noreply.github.com"
            git pull
            git add -A
            timestamp=$(date -u)
            git commit -m "Latest data: ${timestamp}" || exit 0
            git push
